[package]
name = "TgBackup"
version = "0.1.0"
authors = ["Alex Plate <AlexPl292@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
