[package]
name = "TgBackup"
version = "0.1.0"
authors = ["Alex Plate <AlexPl292@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.5", features = ["fs", "sync", "rt-multi-thread"]}
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session = { git = "https://github.com/Lonami/grammers" }
grammers-tl-types = { git = "https://github.com/Lonami/grammers" }
grammers-mtsender = { git = "https://github.com/Lonami/grammers" }
grammers-mtproto = { git = "https://github.com/Lonami/grammers" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
