name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'


jobs:
  pre-checks:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: echo "RUSTFLAGS=-D warnings" >> $GITHUB_ENV

      - name: rustfmt
        run: cargo fmt -- --check

      - name: Run tests
        run: cargo test --verbose
        env:
          TG_ID: ${{ secrets.TG_ID }}
          TG_HASH: ${{ secrets.TG_HASH }}

  build-macos:

    needs: [ pre-checks ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose --release --target x86_64-apple-darwin
        env:
          TG_ID: ${{ secrets.TG_ID }}
          TG_HASH: ${{ secrets.TG_HASH }}

      - name: Install gon
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - name: Set up certs
        env:
          APPLICATION_CERT: ${{ secrets.APPLICATION_CERT }}
          APPLICATION_CERT_PASSWORD: ${{ secrets.APPLICATION_CERT_PASSWORD }}
          KEYCHAIN_PASSWORD: passwrd
        run: |
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/application_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import certificate and provisioning profile from secrets
          echo -n "$APPLICATION_CERT" | base64 --decode --output $CERTIFICATE_PATH

          # Create temporary keychain
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P $APPLICATION_CERT_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Gon notarizing
        env:
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          APP_IDENTITY: ${{ secrets.APP_IDENTITY }}
        run: gon ./gon.json

      - uses: actions/upload-artifact@v2
        with:
          name: tg_backup-x86_64-apple-darwin.zip
          path: tg_backup-x86_64-apple-darwin.zip

  build-windows:

    needs: [ pre-checks ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose --release --target x86_64-pc-windows-msvc
        env:
          TG_ID: ${{ secrets.TG_ID }}
          TG_HASH: ${{ secrets.TG_HASH }}

      - name: zipping
        uses: papeloto/action-zip@v1
        with:
          files: target/x86_64-pc-windows-msvc/release/tg_backup.exe
          dest: tg_backup-x86_64-pc-windows-msvc.zip

      - uses: actions/upload-artifact@v2
        with:
          name: tg_backup-x86_64-pc-windows-msvc.zip
          path: tg_backup-x86_64-pc-windows-msvc.zip

  build-linux:

    needs: [ pre-checks ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
        env:
          TG_ID: ${{ secrets.TG_ID }}
          TG_HASH: ${{ secrets.TG_HASH }}

      - run: chmod +x target/x86_64-unknown-linux-gnu/release/tg_backup

      - name: zipping
        uses: papeloto/action-zip@v1
        with:
          files: target/x86_64-unknown-linux-gnu/release/tg_backup
          dest: tg_backup-x86_64-unknown-linux-gnu.zip

      - uses: actions/upload-artifact@v2
        with:
          name: tg_backup-x86_64-unknown-linux-gnu.zip
          path: tg_backup-x86_64-unknown-linux-gnu.zip

  perform-release:

    needs: [ build-macos, build-windows, build-linux ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: tg_backup-x86_64-unknown-linux-gnu.zip

      - name: Download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: tg_backup-x86_64-pc-windows-msvc.zip

      - name: Download macos artifacts
        uses: actions/download-artifact@v2
        with:
          name: tg_backup-x86_64-apple-darwin.zip

      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          release_notes_file: RELEASE_NOTES.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tg_backup-x86_64-unknown-linux-gnu.zip
            tg_backup-x86_64-pc-windows-msvc.zip
            tg_backup-x86_64-apple-darwin.zip
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - name: Update the Homebrew formula with latest release
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: tg_backup
          download-url: https://github.com/AlexPl292/tg_backup/releases/download/${{ steps.extract-version.outputs.tag-name }}/tg_backup-x86_64-apple-darwin.zip
          homebrew-tap: AlexPl292/homebrew-tg_backup
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
