name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: echo "RUSTFLAGS=-D warnings" >> $GITHUB_ENV
    - name: rustfmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
      env:
        TG_ID: ${{ secrets.TG_ID }}
        TG_HASH: ${{ secrets.TG_HASH }}
    - name: Run tests
      run: cargo test --verbose
      env:
        TG_ID: ${{ secrets.TG_ID }}
        TG_HASH: ${{ secrets.TG_HASH }}
